[package]
name = "multiply"
version = "0.1.0"
authors = ["Kai Mast <kai@kaimast.com>"]
edition = "2024"

[dependencies]
open-lambda = { path="../bindings" }
open-lambda-macros = { path="../macros" }
serde = "1"
