worker_dir: /home/anushka/open-lambda/default-ol/worker
worker_url: localhost
worker_port: "5000"
log_output: true
sandbox: sock
server_mode: lambda
registry: /home/anushka/open-lambda/default-ol/registry
registry_cache_ms: 5000
pkgs_dir: /home/anushka/open-lambda/default-ol/lambda/packages
pip_mirror: ""
mem_pool_mb: 1476
import_cache_tree: /home/anushka/open-lambda/default-ol/default-zygotes-40.yaml
sock_base_path: /home/anushka/open-lambda/default-ol/lambda
sandbox_config: {}
docker:
    runtime: ""
    base_image: ol-min
limits:
    procs: 10
    mem_mb: 50
    cpu_percent: 100
    max_runtime_default: 30
    swappiness: 0
    installer_mem_mb: 500
features:
    reuse_cgroups: false
    import_cache: tree
    downsize_paused_mem: true
    enable_seccomp: true
trace:
    cgroups: false
    memory: false
    evictor: false
    package: false
    latency: false
storage:
    root: private
    scratch: ""
    code: ""
