// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: lambda.proto

package lambda

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LambdaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LambdaRequest) Reset() {
	*x = LambdaRequest{}
	mi := &file_lambda_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LambdaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LambdaRequest) ProtoMessage() {}

func (x *LambdaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lambda_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LambdaRequest.ProtoReflect.Descriptor instead.
func (*LambdaRequest) Descriptor() ([]byte, []int) {
	return file_lambda_proto_rawDescGZIP(), []int{0}
}

func (x *LambdaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LambdaRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type LambdaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LambdaResponse) Reset() {
	*x = LambdaResponse{}
	mi := &file_lambda_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LambdaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LambdaResponse) ProtoMessage() {}

func (x *LambdaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lambda_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LambdaResponse.ProtoReflect.Descriptor instead.
func (*LambdaResponse) Descriptor() ([]byte, []int) {
	return file_lambda_proto_rawDescGZIP(), []int{1}
}

func (x *LambdaResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_lambda_proto protoreflect.FileDescriptor

const file_lambda_proto_rawDesc = "" +
	"\n" +
	"\flambda.proto\x12\x06lambda\"=\n" +
	"\rLambdaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"(\n" +
	"\x0eLambdaResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2H\n" +
	"\rLambdaService\x127\n" +
	"\x06Invoke\x12\x15.lambda.LambdaRequest\x1a\x16.lambda.LambdaResponseB,Z*example.com/open-lambda/grpc-lambda/lambdab\x06proto3"

var (
	file_lambda_proto_rawDescOnce sync.Once
	file_lambda_proto_rawDescData []byte
)

func file_lambda_proto_rawDescGZIP() []byte {
	file_lambda_proto_rawDescOnce.Do(func() {
		file_lambda_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lambda_proto_rawDesc), len(file_lambda_proto_rawDesc)))
	})
	return file_lambda_proto_rawDescData
}

var file_lambda_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lambda_proto_goTypes = []any{
	(*LambdaRequest)(nil),  // 0: lambda.LambdaRequest
	(*LambdaResponse)(nil), // 1: lambda.LambdaResponse
}
var file_lambda_proto_depIdxs = []int32{
	0, // 0: lambda.LambdaService.Invoke:input_type -> lambda.LambdaRequest
	1, // 1: lambda.LambdaService.Invoke:output_type -> lambda.LambdaResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lambda_proto_init() }
func file_lambda_proto_init() {
	if File_lambda_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lambda_proto_rawDesc), len(file_lambda_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lambda_proto_goTypes,
		DependencyIndexes: file_lambda_proto_depIdxs,
		MessageInfos:      file_lambda_proto_msgTypes,
	}.Build()
	File_lambda_proto = out.File
	file_lambda_proto_goTypes = nil
	file_lambda_proto_depIdxs = nil
}
