// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: lambda.proto

package lambda

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LambdaService_Invoke_FullMethodName = "/lambda.LambdaService/Invoke"
)

// LambdaServiceClient is the client API for LambdaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LambdaServiceClient interface {
	Invoke(ctx context.Context, in *LambdaRequest, opts ...grpc.CallOption) (*LambdaResponse, error)
}

type lambdaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLambdaServiceClient(cc grpc.ClientConnInterface) LambdaServiceClient {
	return &lambdaServiceClient{cc}
}

func (c *lambdaServiceClient) Invoke(ctx context.Context, in *LambdaRequest, opts ...grpc.CallOption) (*LambdaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LambdaResponse)
	err := c.cc.Invoke(ctx, LambdaService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LambdaServiceServer is the server API for LambdaService service.
// All implementations must embed UnimplementedLambdaServiceServer
// for forward compatibility.
type LambdaServiceServer interface {
	Invoke(context.Context, *LambdaRequest) (*LambdaResponse, error)
	mustEmbedUnimplementedLambdaServiceServer()
}

// UnimplementedLambdaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLambdaServiceServer struct{}

func (UnimplementedLambdaServiceServer) Invoke(context.Context, *LambdaRequest) (*LambdaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedLambdaServiceServer) mustEmbedUnimplementedLambdaServiceServer() {}
func (UnimplementedLambdaServiceServer) testEmbeddedByValue()                       {}

// UnsafeLambdaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LambdaServiceServer will
// result in compilation errors.
type UnsafeLambdaServiceServer interface {
	mustEmbedUnimplementedLambdaServiceServer()
}

func RegisterLambdaServiceServer(s grpc.ServiceRegistrar, srv LambdaServiceServer) {
	// If the following call pancis, it indicates UnimplementedLambdaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LambdaService_ServiceDesc, srv)
}

func _LambdaService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LambdaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LambdaServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LambdaService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LambdaServiceServer).Invoke(ctx, req.(*LambdaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LambdaService_ServiceDesc is the grpc.ServiceDesc for LambdaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LambdaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lambda.LambdaService",
	HandlerType: (*LambdaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _LambdaService_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lambda.proto",
}
