#!/bin/bash
if [[ $(cd worker && gofmt -d .) ]]; then
	cat <<\EOF
Error:  format check failed
        Please format your code with 'go fmt' and commit again
EOF
	exit 1
fi

if $(cd worker && go vet) >/dev/null 2>&1 != 0; then
	cat <<\EOF
Error:  vet check failed
        Please vet your code in worker/ with 'go vet' and commit again
        All code must pass vet to commit
EOF
	exit 1
fi

