# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  for i in 32000..32999
    config.vm.network :forwarded_port, guest: i, host: i
  end

  config.vm.provision "shell", path: "../../quickstart/startup.sh"
  # config.vm.provision "ansible" do |ansible|
  #  ansible.verbose = "v"
  #   ansible.playbook = "playbook.yml"
  #   ansible.groups = {
  #       "common" => ["default"]
  #   }
  # end
end
