# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\" \n\x0b\x45\x63hoRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\"#\n\x0c\x45\x63hoResponse\x12\x13\n\x0bjson_result\x18\x01 \x01(\t2C\n\x0b\x45\x63hoService\x12\x34\n\x0bSendRequest\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=20
  _globals['_ECHOREQUEST']._serialized_end=52
  _globals['_ECHORESPONSE']._serialized_start=54
  _globals['_ECHORESPONSE']._serialized_end=89
  _globals['_ECHOSERVICE']._serialized_start=91
  _globals['_ECHOSERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
