#!/bin/bash

# test the version of go (lower versions use -tabs for formatting)
if $(gofmt -tabs <<<"" > /dev/null 2>&1); then
    cat <<EOF
Warning: golang version lower than 1.3.0
Please update golang to ensure gofmt could work correctly
EOF
    tabflag=' -tabs'
fi

# test for non-empty gofmt (this outputs diffs) (excluding vendor)
if [[ $(cd worker && \
    gofmt -d${tabflag} \
    $(find . -type f ! -path './vendor/*' -name '*.go')) ]]; then
	cat <<EOF
Error: format check failed
Please format "worker" directory with the following command and commit again:

    gofmt -w -l${tabflag} \$(find $PWD/worker ! -path '*/vendor/*' -name '*.go')
EOF
	exit 1
fi


$( cd worker && go vet ) || {
	cat <<\EOF
Error:  vet check failed
        Please vet your code in worker/ with 'go vet' and commit again
        All code must pass vet to commit
EOF
	exit 1
}

