# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.hostname = "host-box"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  for i in 32000..32999
    config.vm.network :forwarded_port, guest: i, host: i
  end

  config.vm.provision "shell", path: "startup.sh"

  # Comment the above line and uncomment the lines below to use ansible
  # config.vm.provision "ansible" do |ansible|
  #   ansible.verbose = "v"
  #   ansible.playbook = "playbook.yml"
  #   ansible.groups = {
  #       "common" => ["default"]
  #   }
  # end
end
