[package]
name = "open-lambda-proxy-protocol"
version = "0.1.0"
authors = ["Kai Mast <kaimast@cs.wisc.edu>"]
edition = "2021"

[dependencies]
serde = { version="1", features=["derive"] }
serde_bytes = "0.11"
