# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wsmanager_pb2 as wsmanager__pb2


class WsManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostToConnection = channel.unary_unary(
                '/proto.WsManager/PostToConnection',
                request_serializer=wsmanager__pb2.PostToConnectionRequest.SerializeToString,
                response_deserializer=wsmanager__pb2.PostToConnectionResponse.FromString,
                )


class WsManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostToConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WsManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostToConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.PostToConnection,
                    request_deserializer=wsmanager__pb2.PostToConnectionRequest.FromString,
                    response_serializer=wsmanager__pb2.PostToConnectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.WsManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WsManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostToConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.WsManager/PostToConnection',
            wsmanager__pb2.PostToConnectionRequest.SerializeToString,
            wsmanager__pb2.PostToConnectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
