# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsmanager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwsmanager.proto\x12\x05proto\"=\n\x17PostToConnectionRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x15\n\rconnection_id\x18\x02 \x01(\t\":\n\x18PostToConnectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2`\n\tWsManager\x12S\n\x10PostToConnection\x12\x1e.proto.PostToConnectionRequest\x1a\x1f.proto.PostToConnectionResponseB\nZ\x08./;protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wsmanager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./;proto'
  _POSTTOCONNECTIONREQUEST._serialized_start=26
  _POSTTOCONNECTIONREQUEST._serialized_end=87
  _POSTTOCONNECTIONRESPONSE._serialized_start=89
  _POSTTOCONNECTIONRESPONSE._serialized_end=147
  _WSMANAGER._serialized_start=149
  _WSMANAGER._serialized_end=245
# @@protoc_insertion_point(module_scope)
